# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/openstal',
                'doc_host': 'https://fenke.github.io',
                'git_url': 'https://github.com/fenke/openstal',
                'lib_path': 'openstal'},
  'syms': {'openstal.core': {'openstal.core.foo': ('core.html#foo', 'openstal/core.py')}}}
